name: Generate Tokens On Input

on:
  schedule:
  - cron: "0 6 * * 1-5"

jobs:
  generate_tokens:
    runs-on: macos-latest
    steps:
    - name: Install Dependencies
      run: npm install
    - name: Build Style Dictionary
      run: style-dictionary build
